# GitHub Action to automate the identification of common misspellings in text files.
# https://github.com/codespell-project/actions-codespell
# https://github.com/codespell-project/codespell
name: codespell
on: [push, pull_request]
jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: codespell-project/actions-codespell@master
      with:
        check_filenames: true
        skip: '*.jpg,*.png,./.git,./yarn.lock,./src/app/style/fonts/*,./src/common/i18n/text_cs.ts,./src/common/i18n/text_de.ts,./src/common/i18n/text_es.ts,./src/common/i18n/text_fr.ts'
          # For glob options see: https://docs.python.org/3/library/fnmatch.html
        #ignore_words_list: ""
